apiVersion: v1
kind: LimitRange
metadata:
  name: security-lab-defaults
  namespace: security-lab
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 500m
        memory: 256Mi
